version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:delegated
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: "production"
