version: '3.8'
services:
  web:
    build: .
    environment:
      NODE_ENV: development
      PORT: 3000
    working_dir: /app
    volumes:
      - ".:/app"
      - /app/node_modules
    ports:
    - 3000:3000

