import type { NextPage, Metadata } from 'next'
import Image from 'next/image'

import { Locale } from '../../../i18n.config'
import drop from '../../assets/images/icons/drop.svg'
import clock from '../../assets/images/icons/clock.svg'
import calendar from '../../assets/images/icons/calendar.svg'
import whoWeAreMain from '../../assets/images/WhoWeAreMain.svg'
import purpose from '../../assets/images/purpose.png'
import { getDictionary } from '../../../dictionary'
import { convertBreaks } from '../../common/helpers'
import { Navbar, Features, Plans, Benefits, ContactBanner, Footer } from '../../components'

export const metadata: Metadata = {
  title: 'Hermes Logistic',
  description: 'Generated by create next app',
}

const Home: NextPage<{ params: { lang: Locale } }> = async ({ params: { lang } }) => {
  const { mainSection, menu, whoWeAre, purposeAchieve, benefits, features, pricing, contact } =
    await getDictionary(lang)

  return (
    <>
      <header className="home">
        <Navbar lang={menu} currentLang={lang} />
        <div className="intro w-100">
          <h1 style={{ maxWidth: '1500px' }} className="fw-semibold display-2 px-3 px-md-0 mt-5 mx-auto">
            {mainSection.title}
          </h1>
          <p className="fs-18 fw-semibold mx-auto mt-4 mb-5 px-3 px-md-0" style={{ maxWidth: '650px' }}>
            {mainSection.subtitle}
          </p>
          <button type="button" className="btn btn-secondary rounded-pill fw-bold fs-5 px-5 py-3 mb-3">
            {mainSection.cta}
          </button>
        </div>
        <div className="info container">
          <div className="info-element">
            <Image src={drop} alt="drop" width={30} height={30} />
            <span className="line" />
            <p className="justify-content-start">
              <span className="fs-1 fw-semibold pe-3">10%</span>
              <span>{mainSection.fuel}</span>
            </p>
          </div>
          <div className="info-element">
            <Image src={clock} alt="clock" width={30} height={30} />
            <span className="line" />
            <p>
              <span className="fs-1 fw-semibold pe-3">20%</span>
              <span>{convertBreaks(mainSection.hours)}</span>
            </p>
          </div>
          <div className="info-element">
            <Image src={calendar} alt="calendar" width={30} height={30} />
            <span className="line" />
            <p>
              <span className="fs-1 fw-semibold pe-3">40%</span>
              <span>{convertBreaks(mainSection.cost)}</span>
            </p>
          </div>
        </div>
      </header>

      <main className="container-fluid px-0 pt-5">
        <section
          id="who-we-are"
          className="who-we-are-section py-5 d-flex justify-content-evenly align-items-center mw-1200 px-3 px-xl-0"
        >
          <div style={{ maxWidth: '510px' }}>
            <span className="fs-12 text-sunset fw-semibold">{whoWeAre.section}</span>
            <h2 className="display-5 fw-semibold lh-base py-4 mb-0">{convertBreaks(whoWeAre.title)}</h2>
            <Image
              src={whoWeAreMain}
              alt="Who We Are"
              width={650}
              height={550}
              className="mw-100 d-inline-block d-lg-none"
            />
            <p className="fs-5">{convertBreaks(whoWeAre.text)}</p>
          </div>
          <Image
            src={whoWeAreMain}
            alt="Who We Are"
            width={650}
            height={550}
            className="mw-100 d-none d-lg-inline-block"
          />
        </section>

        <section>
          <ul id="CustomTabs" role="tablist">
            <li role="presentation">
              <button
                className="nav-link active"
                id="purpose-tab"
                data-bs-toggle="tab"
                data-bs-target="#purpose-tab-pane"
                type="button"
                role="tab"
                aria-controls="purpose-tab-pane"
                aria-selected="true"
                tabIndex={-1}
              >
                {purposeAchieve.tab1}
              </button>
            </li>
            <li className="nav-item" role="presentation">
              <button
                className="nav-link"
                id="archive-tab"
                data-bs-toggle="tab"
                data-bs-target="#archive-tab-pane"
                type="button"
                role="tab"
                aria-controls="archive-tab-pane"
                aria-selected="false"
                tabIndex={-1}
              >
                {purposeAchieve.tab2}
              </button>
            </li>
          </ul>
          <div className="tab-content" id="CustomTabsContent">
            <div
              className="tab-pane fade show active"
              id="purpose-tab-pane"
              role="tabpanel"
              aria-labelledby="purpose-tab"
              tabIndex={0}
            >
              <div className="tab-custom-content">
                <Image src={purpose} alt="Our purpose" width={550} className="mw-100 d-none d-lg-inline-block" />
                <div style={{ maxWidth: '410px' }}>
                  <h2 className="display-5 fw-semibold lh-base pb-4 mb-0">{purposeAchieve.title1}</h2>
                  <Image src={purpose} alt="Our purpose" width={550} className="mw-100 d-lg-inline-block d-lg-none" />
                  <p className="fs-5">{purposeAchieve.text1}</p>
                </div>
              </div>
            </div>
            <div
              className="tab-pane fade"
              id="archive-tab-pane"
              role="tabpanel"
              aria-labelledby="archive-tab"
              tabIndex={0}
            >
              <div className="tab-custom-content">
                <div style={{ maxWidth: '410px' }}>
                  <h2 className="display-5 fw-semibold pb-4 mb-0">{purposeAchieve.title2}</h2>
                  <Image src={purpose} alt="Our purpose" width={550} className="mw-100 d-inline-block d-lg-none" />
                  <p className="fs-5">{purposeAchieve.text2}</p>
                </div>
                <Image src={purpose} alt="Our purpose" width={550} className="mw-100 d-none d-lg-inline-block" />
              </div>
            </div>
          </div>
        </section>

        <Benefits lang={benefits} />

        <Features lang={features} />

        <Plans lang={pricing} />

        <ContactBanner title={contact.title} subtitle={contact.subtitle} ctaText={contact.cta} />
      </main>
      <Footer />
    </>
  )
}

export default Home
