import type { NextPage, Metadata } from 'next'
import Image from 'next/image'

import { Locale } from '../../../i18n.config'
import { Navbar, Features, Plans, Benefits } from '../../components'
import drop from '../../assets/images/icons/drop.svg'
import clock from '../../assets/images/icons/clock.svg'
import calendar from '../../assets/images/icons/calendar.svg'
import whoWeAreMain from '../../assets/images/WhoWeAreMain.svg'
import purpose from '../../assets/images/purpose.png'
import banner from '../../assets/images/banner.svg'
import fb from '../../assets/images/icons/fb.svg'
import ins from '../../assets/images/icons/ins.svg'
import x from '../../assets/images/icons/x.svg'
import tel from '../../assets/images/icons/tel.svg'
import { getDictionary } from '../../../dictionary'

export const metadata: Metadata = {
  title: 'Hermes Logistic',
  description: 'Generated by create next app',
}

const Home: NextPage<{ params: { lang: Locale } }> = async ({ params: { lang } }) => {
  const { home } = await getDictionary(lang)

  return (
    <>
      <header>
        <Navbar />
        <div className="intro w-100">
          <h1 className="fw-semibold display-2 px-3 px-md-0 mt-5">Lorem Ipsum Dolor Sit Amet</h1>
          <p className="fs-18 fw-semibold mx-auto mt-4 mb-5 px-3 px-md-0" style={{ maxWidth: '650px' }}>
            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti
            atque corrupti.
          </p>
          <button type="button" className="btn btn-secondary rounded-pill fw-bold fs-5 px-5 py-3 mb-3">
            {home.test}
          </button>
        </div>
        <div className="info container">
          <div className="info-element">
            <Image src={drop} alt="drop" width={30} height={30} />
            <span className="line" />
            <p className="justify-content-start">
              <span className="fs-1 fw-semibold pe-3">10%</span>
              <span>FUEL SAVINGS</span>
            </p>
          </div>
          <div className="info-element">
            <Image src={clock} alt="clock" width={30} height={30} />
            <span className="line" />
            <p>
              <span className="fs-1 fw-semibold">20%</span>
              <span>
                SAVINGS IN WORK
                <br />
                HOURS
              </span>
            </p>
          </div>
          <div className="info-element">
            <Image src={calendar} alt="calendar" width={30} height={30} />
            <span className="line" />
            <p>
              <span className="fs-1 fw-semibold">40%</span>
              <span>
                COST PRODUCTION
                <br />
                FROM ERROR DELAYS.
              </span>
            </p>
          </div>
        </div>
      </header>

      <main className="container-fluid px-0 pt-5">
        <section
          id="who-we-are"
          className="who-we-are-section py-5 d-flex justify-content-evenly align-items-center mw-1200 px-3 px-xl-0"
        >
          <div style={{ maxWidth: '510px' }}>
            <span className="fs-12 text-sunset fw-semibold">WHO WE ARE</span>
            <h2 className="display-5 fw-semibold lh-base py-4 mb-0">
              Hermes
              <br />
              Logistic Company
            </h2>
            <Image
              src={whoWeAreMain}
              alt="Who We Are"
              width={650}
              height={550}
              className="mw-100 d-inline-block d-lg-none"
            />
            <p className="fs-5">
              We are Hermes Fleet Management, a leading technology provider offering an innovative solution to
              streamline vehicle fleet operations.
              <br />
              <br />
              Our platform empowers companies to optimize their delivery routes, lower operational costs, and drive
              customer satisfaction. By leveraging our advanced reporting and real-time analysis, businesses can make
              strategic decisions for enhanced efficiency and profitability.
            </p>
          </div>
          <Image
            src={whoWeAreMain}
            alt="Who We Are"
            width={650}
            height={550}
            className="mw-100 d-none d-lg-inline-block"
          />
        </section>

        <section>
          <ul id="CustomTabs" role="tablist">
            <li role="presentation">
              <button
                className="nav-link active"
                id="purpose-tab"
                data-bs-toggle="tab"
                data-bs-target="#purpose-tab-pane"
                type="button"
                role="tab"
                aria-controls="purpose-tab-pane"
                aria-selected="true"
                tabIndex={-1}
              >
                Our Purpose
              </button>
            </li>
            <li className="nav-item" role="presentation">
              <button
                className="nav-link"
                id="archive-tab"
                data-bs-toggle="tab"
                data-bs-target="#archive-tab-pane"
                type="button"
                role="tab"
                aria-controls="archive-tab-pane"
                aria-selected="false"
                tabIndex={-1}
              >
                What do we Want To Achieve?
              </button>
            </li>
          </ul>
          <div className="tab-content" id="CustomTabsContent">
            <div
              className="tab-pane fade show active"
              id="purpose-tab-pane"
              role="tabpanel"
              aria-labelledby="purpose-tab"
              tabIndex={0}
            >
              <div className="tab-custom-content">
                <Image src={purpose} alt="Our purpose" width={550} className="mw-100 d-none d-lg-inline-block" />
                <div style={{ maxWidth: '410px' }}>
                  <h2 className="display-5 fw-semibold lh-base pb-4 mb-0">Our Purpose</h2>
                  <Image src={purpose} alt="Our purpose" width={550} className="mw-100 d-lg-inline-block d-lg-none" />
                  <p className="fs-5">
                    Use Intelligent Route Optimization to transform the way companies manage their vehicles fleet, using
                    Hermes will help them to to optimize delivery routes. By considering factors like traffic, delivery
                    windows, and package volume, businesses can reduce travel time, fuel consumption, and operational
                    costs. The intelligent route optimization feature ensures efficient resource utilization and
                    maximizes delivery efficiency.
                  </p>
                </div>
              </div>
            </div>
            <div
              className="tab-pane fade"
              id="archive-tab-pane"
              role="tabpanel"
              aria-labelledby="archive-tab"
              tabIndex={0}
            >
              <div className="tab-custom-content">
                <div style={{ maxWidth: '410px' }}>
                  <h2 className="display-5 fw-semibold pb-4 mb-0">What do we Want To Achieve?</h2>
                  <Image src={purpose} alt="Our purpose" width={550} className="mw-100 d-inline-block d-lg-none" />
                  <p className="fs-5">
                    To lead the fleet management industry with cutting-edge technology and exceptional service,
                    expanding nationally and internationally to positively impact the logistics of companies worldwide.
                  </p>
                </div>
                <Image src={purpose} alt="Our purpose" width={550} className="mw-100 d-none d-lg-inline-block" />
              </div>
            </div>
          </div>
        </section>

        <Benefits />

        <Features />

        <Plans />

        <section id="contact" className="w-100 banner-section">
          <div className="banner">
            <div>
              <h2 className="display-5 fw-semibold">CTA title Banner Here</h2>
              <p className="fs-5 mb-4">
                Sed ut perspiciatis unde omnis iste natus error sit
                <br />
                voluptatem accusantium.
              </p>
              <button type="button" className="btn btn-secondary rounded-pill fs-5 fw-bold">
                CTA Text Here
              </button>
            </div>
            <Image src={banner} alt="Banner" width={440} height={565} className="mw-100" />
          </div>
        </section>
      </main>
      <footer className="w-100">
        <div className="mw-1200">
          <div className="d-flex justify-content-between align-items-center pb-0 pb-md-5">
            <Image src="/small-logo.svg" alt="Hermes Logistic" width={170} height={70} />
            <ul className="social">
              <li>
                <a href="http://google.com" target="_blank" rel="noopener noreferrer">
                  <Image src={fb} alt="Facebook" width={30} height={30} />
                </a>
              </li>
              <li>
                <a href="http://google.com" target="_blank" rel="noopener noreferrer">
                  <Image src={ins} alt="Instagram" width={30} height={30} />
                </a>
              </li>
              <li>
                <a href="http://google.com" target="_blank" rel="noopener noreferrer">
                  <Image src={x} alt="X" width={30} height={30} />
                </a>
              </li>
              <li>
                <a href="http://google.com" target="_blank" rel="noopener noreferrer">
                  <Image src={tel} alt="Telegram" width={30} height={30} />
                </a>
              </li>
            </ul>
          </div>

          <div className="terms">
            <span className="fs-12">©Hermes Company. All Rights Reserved</span>
            <a href="http://google.com" target="_blank" rel="noopener noreferrer" className="fs-12">
              Privacy Policy
            </a>
            <a href="http://google.com" target="_blank" rel="noopener noreferrer" className="fs-12">
              Terms & Conditions
            </a>
          </div>
        </div>
      </footer>
    </>
  )
}

export default Home
