import type { NextPage, Metadata } from 'next'
import Image from 'next/image'

import '@/styles/services.scss'

import ServicesHeader from '../../../assets/images/services_header.svg'
import service1 from '../../../assets/images/icons/service1.svg'
import service2 from '../../../assets/images/icons/service2.svg'
import service3 from '../../../assets/images/icons/service3.svg'
import service4 from '../../../assets/images/icons/service4.svg'
import service5 from '../../../assets/images/icons/service5.svg'
import service6 from '../../../assets/images/icons/service6.svg'
import service1img from '../../../assets/images/slider/service1.png'
import service2img from '../../../assets/images/slider/service2.png'
import service3img from '../../../assets/images/slider/service3.png'
import service4img from '../../../assets/images/slider/service4.png'
import service5img from '../../../assets/images/slider/service5.png'
import service6img from '../../../assets/images/slider/service6.png'
import { Locale } from '../../../../i18n.config'
import { getDictionary } from '../../../../dictionary'
import { ContactBanner, Footer, ListWithReadMore, Navbar } from '../../../components'

export const metadata: Metadata = {
  title: 'Hermes Logistic | Services',
  description: 'Generated by create next app',
}

const Services: NextPage<{ params: { lang: Locale } }> = async ({ params: { lang } }) => {
  const { services, menu, contact } = await getDictionary(lang)
  const { info } = services

  const servicesHelper = [
    {
      icon: service1,
      image: service1img,
    },
    {
      icon: service2,
      image: service2img,
    },
    {
      icon: service3,
      image: service3img,
    },
    {
      icon: service4,
      image: service4img,
    },
    {
      icon: service5,
      image: service5img,
    },
    {
      icon: service6,
      image: service6img,
    },
  ]
  return (
    <>
      <header className="services">
        <Navbar lang={menu} currentLang={lang} />
        <div className="w-100">
          <h1 className="w-100 display-1 fw-semibold mb-0 mb-lg-5">{services.title}</h1>
          <Image src={ServicesHeader} height={350} alt="Services" style={{ width: '92%' }} />
        </div>
      </header>

      <main className="container-fluid px-0 pt-0 pt-md-5">
        <section id="services-grid" className="w-100">
          <div className="mw-1200">
            <div className="text-center mb-5 px-3">
              <span className="fw-semibold fs-12 text-sunset w-100 d-block">{info.section}</span>
              <h2 style={{ maxWidth: '400px' }} className="mt-4 pb-3 display-5 fw-semibold mx-auto">
                {info.title}
              </h2>
              <p style={{ maxWidth: '550px' }} className="fs-5 mx-auto">
                {info.description}
              </p>
            </div>
            <div className="services-grid">
              {info.grid.map((el: { title: string; items: string[] }, idx) => (
                <div className="services-item" key={el.title.replace(' ', '-')}>
                  <Image src={servicesHelper[idx].image} alt={el.title} className="img" />
                  <h3 className="fs-1">
                    <Image src={servicesHelper[idx].icon} height={40} width={40} alt={el.title} />
                    <span>{el.title}</span>
                  </h3>
                  <ListWithReadMore
                    more={lang === 'en' ? 'Read more' : 'Ver más'}
                    less={lang === 'en' ? 'Read less' : 'Ver menos'}
                    list={el.items}
                  />
                </div>
              ))}
            </div>
          </div>
        </section>
        <div id="services-helper" />

        <ContactBanner title={contact.title} subtitle={contact.subtitle} ctaText={contact.cta} />
      </main>
      <Footer />
    </>
  )
}

export default Services
