name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-east4
jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js (NPM)
        uses: actions/setup-node@master
        with:
          node-version: '18.x'

      - name: Use cached node_modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Development
        run: npm run build
        env:
          CI: false

      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: build
  deploy-bucket:
    name: Deploy to bucket
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Download Artifact
        uses: actions/download-artifact@main
        with:
          name: build
          path: build

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/setup-gcloud@v0.2.1
        
      - name: GET KEY
        run: echo $GOOGLE_SERVICE_ACCOUNT_CREDENTIALS | base64 -d > ./gcloud-api-key.json
      
      - name: GET KEY
        run: echo $GOOGLE_SERVICE_ACCOUNT_CREDENTIALS | base64 -d > ./gcloud-api-key.json
      
      - name: Authentication
        run: gcloud auth activate-service-account --key-file=gcloud-api-key.json

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1

      # Build and push image to Google Container Registry
      - name: rsync
        run: gsutil rsync -r . gs://website-website-gcp-development
        working-directory: build